// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/ratelimit.proto

package ratelimitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRateLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for what we're rate limiting
	// Examples: "user:123", "ip:192.168.1.1", "apikey:abc123"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Maximum number of requests allowed
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Time window in seconds (e.g., 60 for "10 requests per minute")
	WindowSeconds int32 `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	// Optional: namespace for organizing limits
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitRequest) Reset() {
	*x = CheckRateLimitRequest{}
	mi := &file_api_proto_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitRequest) ProtoMessage() {}

func (x *CheckRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRateLimitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRateLimitRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckRateLimitRequest) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *CheckRateLimitRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CheckRateLimitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the request is allowed
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// How many requests remaining in current window
	Remaining int32 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// When the rate limit resets
	ResetAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	// If denied, how long to wait before retry (seconds)
	RetryAfterSeconds int32 `protobuf:"varint,4,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	// Current limit being applied
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitResponse) Reset() {
	*x = CheckRateLimitResponse{}
	mi := &file_api_proto_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitResponse) ProtoMessage() {}

func (x *CheckRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckRateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckRateLimitResponse) GetResetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetAt
	}
	return nil
}

func (x *CheckRateLimitResponse) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *CheckRateLimitResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_api_proto_ratelimit_proto protoreflect.FileDescriptor

const file_api_proto_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/ratelimit.proto\x12\fratelimit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\x15CheckRateLimitRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\x05R\rwindowSeconds\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"\xcd\x01\n" +
	"\x16CheckRateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x125\n" +
	"\breset_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aresetAt\x12.\n" +
	"\x13retry_after_seconds\x18\x04 \x01(\x05R\x11retryAfterSeconds\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit2q\n" +
	"\x12RateLimiterService\x12[\n" +
	"\x0eCheckRateLimit\x12#.ratelimit.v1.CheckRateLimitRequest\x1a$.ratelimit.v1.CheckRateLimitResponseBQZOgithub.com/burakmert236/rate-limiter-service/api/proto/ratelimit/v1;ratelimitv1b\x06proto3"

var (
	file_api_proto_ratelimit_proto_rawDescOnce sync.Once
	file_api_proto_ratelimit_proto_rawDescData []byte
)

func file_api_proto_ratelimit_proto_rawDescGZIP() []byte {
	file_api_proto_ratelimit_proto_rawDescOnce.Do(func() {
		file_api_proto_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ratelimit_proto_rawDesc), len(file_api_proto_ratelimit_proto_rawDesc)))
	})
	return file_api_proto_ratelimit_proto_rawDescData
}

var file_api_proto_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_ratelimit_proto_goTypes = []any{
	(*CheckRateLimitRequest)(nil),  // 0: ratelimit.v1.CheckRateLimitRequest
	(*CheckRateLimitResponse)(nil), // 1: ratelimit.v1.CheckRateLimitResponse
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_api_proto_ratelimit_proto_depIdxs = []int32{
	2, // 0: ratelimit.v1.CheckRateLimitResponse.reset_at:type_name -> google.protobuf.Timestamp
	0, // 1: ratelimit.v1.RateLimiterService.CheckRateLimit:input_type -> ratelimit.v1.CheckRateLimitRequest
	1, // 2: ratelimit.v1.RateLimiterService.CheckRateLimit:output_type -> ratelimit.v1.CheckRateLimitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_ratelimit_proto_init() }
func file_api_proto_ratelimit_proto_init() {
	if File_api_proto_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ratelimit_proto_rawDesc), len(file_api_proto_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ratelimit_proto_goTypes,
		DependencyIndexes: file_api_proto_ratelimit_proto_depIdxs,
		MessageInfos:      file_api_proto_ratelimit_proto_msgTypes,
	}.Build()
	File_api_proto_ratelimit_proto = out.File
	file_api_proto_ratelimit_proto_goTypes = nil
	file_api_proto_ratelimit_proto_depIdxs = nil
}
